// lex.yy.cpp generated by reflex 6.1.0 from Lexer.txt

#define REFLEX_VERSION "6.1.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_graphs_file         "Lexer.dot.gv"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_outfile             "lex.yy.cpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual int lex(void);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  int lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int Lexer::lex(void)
{
  static const char *REGEX_INITIAL = "(?m)(//[^\\x0a]*)|(/\\*(?:[^\\x2a]|\\*+[^\\x2a/])*\\*/)|([\\x09\\x0a\\x20]+)|([0-9]+)|((?:\\Qvar\\E))|((?:\\Qfunc\\E))|((?:\\Qreturn\\E))|((?:\\Qif\\E))|((?:\\Qelse\\E))|((?:\\Qfor\\E))|((?:\\Qtrue\\E))|((?:\\Qfalse\\E))|((?:\\Qint\\E))|((?:\\Qbool\\E))|((?:\\Qref\\E))|((?:\\Qprintln\\E))|((?:\\Qprint\\E))|([A-Z_a-z][0-9A-Z_a-z]*)|((?:\\Q+\\E))|((?:\\Q-\\E))|((?:\\Q*\\E))|((?:\\Q/\\E))|((?:\\Q%\\E))|((?:\\Q==\\E))|((?:\\Q!=\\E))|((?:\\Q<\\E))|((?:\\Q>\\E))|((?:\\Q>=\\E))|((?:\\Q<=\\E))|((?:\\Q&&\\E))|((?:\\Q||\\E))|((?:\\Q!\\E))|((?:\\Q:=\\E))|((?:\\Q=\\E))|((?:\\Q&\\E))|((?:\\Q(\\E))|((?:\\Q)\\E))|((?:\\Q{\\E))|((?:\\Q}\\E))|((?:\\Q;\\E))|((?:\\Q,\\E))|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
#line 45 "Lexer.txt"
{return END_FILE;}
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule Lexer.txt:3: \/\/[^\n]* :
#line 3 "Lexer.txt"
{/* ignore */}
            break;
          case 2: // rule Lexer.txt:4: \/\*([^*]|\*+[^*/])*\*\/ :
#line 4 "Lexer.txt"
{/* ignore */}
            break;
          case 3: // rule Lexer.txt:5: [ \t\n]+ :
#line 5 "Lexer.txt"
{ /* ignore */ }
            break;
          case 4: // rule Lexer.txt:6: [0-9]+ :
#line 6 "Lexer.txt"
{return INT_LIT;}
            break;
          case 5: // rule Lexer.txt:7: "var" :
#line 7 "Lexer.txt"
{return KW_VAR;}
            break;
          case 6: // rule Lexer.txt:8: "func" :
#line 8 "Lexer.txt"
{return KW_FUNC;}
            break;
          case 7: // rule Lexer.txt:9: "return" :
#line 9 "Lexer.txt"
{return KW_RETURN;}
            break;
          case 8: // rule Lexer.txt:10: "if" :
#line 10 "Lexer.txt"
{return KW_IF;}
            break;
          case 9: // rule Lexer.txt:11: "else" :
#line 11 "Lexer.txt"
{return KW_ELSE;}
            break;
          case 10: // rule Lexer.txt:12: "for" :
#line 12 "Lexer.txt"
{return KW_FOR;}
            break;
          case 11: // rule Lexer.txt:13: "true" :
#line 13 "Lexer.txt"
{return KW_TRUE;}
            break;
          case 12: // rule Lexer.txt:14: "false" :
#line 14 "Lexer.txt"
{return KW_FALSE;}
            break;
          case 13: // rule Lexer.txt:15: "int" :
#line 15 "Lexer.txt"
{return KW_INT;}
            break;
          case 14: // rule Lexer.txt:16: "bool" :
#line 16 "Lexer.txt"
{return KW_BOOL;}
            break;
          case 15: // rule Lexer.txt:17: "ref" :
#line 17 "Lexer.txt"
{return KW_REF;}
            break;
          case 16: // rule Lexer.txt:18: "println" :
#line 18 "Lexer.txt"
{return KW_PRINTLN;}
            break;
          case 17: // rule Lexer.txt:19: "print" :
#line 19 "Lexer.txt"
{return KW_PRINT;}
            break;
          case 18: // rule Lexer.txt:20: [a-zA-Z_][a-zA-Z0-9_]* :
#line 20 "Lexer.txt"
{return IDENTI;}
            break;
          case 19: // rule Lexer.txt:21: "+" :
#line 21 "Lexer.txt"
{return OP_ADD;}
            break;
          case 20: // rule Lexer.txt:22: "-" :
#line 22 "Lexer.txt"
{return OP_SUB;}
            break;
          case 21: // rule Lexer.txt:23: "*" :
#line 23 "Lexer.txt"
{return OP_MULT;}
            break;
          case 22: // rule Lexer.txt:24: "/" :
#line 24 "Lexer.txt"
{return OP_DIV;}
            break;
          case 23: // rule Lexer.txt:25: "%" :
#line 25 "Lexer.txt"
{return OP_MOD;}
            break;
          case 24: // rule Lexer.txt:26: "==" :
#line 26 "Lexer.txt"
{return OP_EQ;}
            break;
          case 25: // rule Lexer.txt:27: "!=" :
#line 27 "Lexer.txt"
{return OP_NEQ;}
            break;
          case 26: // rule Lexer.txt:28: "<" :
#line 28 "Lexer.txt"
{return OP_LT;}
            break;
          case 27: // rule Lexer.txt:29: ">" :
#line 29 "Lexer.txt"
{return OP_GT;}
            break;
          case 28: // rule Lexer.txt:30: ">=" :
#line 30 "Lexer.txt"
{return OP_GTE;}
            break;
          case 29: // rule Lexer.txt:31: "<=" :
#line 31 "Lexer.txt"
{return OP_LTE;}
            break;
          case 30: // rule Lexer.txt:32: "&&" :
#line 32 "Lexer.txt"
{return OP_AND;}
            break;
          case 31: // rule Lexer.txt:33: "||" :
#line 33 "Lexer.txt"
{return OP_OR;}
            break;
          case 32: // rule Lexer.txt:34: "!" :
#line 34 "Lexer.txt"
{return OP_NOT;}
            break;
          case 33: // rule Lexer.txt:35: ":=" :
#line 35 "Lexer.txt"
{return OP_SHORT_DEC;}
            break;
          case 34: // rule Lexer.txt:36: "=" :
#line 36 "Lexer.txt"
{return OP_ASSIGN;}
            break;
          case 35: // rule Lexer.txt:37: "&" :
#line 37 "Lexer.txt"
{return OP_ADDR;}
            break;
          case 36: // rule Lexer.txt:38: "(" :
#line 38 "Lexer.txt"
{return OPEN_PAR;}
            break;
          case 37: // rule Lexer.txt:39: ")" :
#line 39 "Lexer.txt"
{return CLOSED_PAR;}
            break;
          case 38: // rule Lexer.txt:40: "{" :
#line 40 "Lexer.txt"
{return OPEN_BRA;}
            break;
          case 39: // rule Lexer.txt:41: "}" :
#line 41 "Lexer.txt"
{return CLOSED_BRA;}
            break;
          case 40: // rule Lexer.txt:42: ";" :
#line 42 "Lexer.txt"
{return SEMICOLON;}
            break;
          case 41: // rule Lexer.txt:43: "," :
#line 43 "Lexer.txt"
{return COMMA;}

            break;
          case 42: // rule Lexer.txt:46: . :
#line 46 "Lexer.txt"
{return UNK;}
            break;
        }
  }
}
