#include "Lexer.hpp"

Token Lexer::nextToken(){
    do{
        if(ch_==' '||ch_=='\t'||ch_=='\n'){
            consume();
            while(ch_==' '||ch_=='\t'||ch_=='\n'){
                consume();
            }
        }
        if(ch_=='/'){
            consume();
            if(ch_=='/'){
                while(ch_!='\n'&&ch_!=EOF){
                    consume();
                }
                continue;
            }
            if(ch_=='*'){
                consume();
                while(true){
                    if(ch_==EOF){
                        break;
                    }
                    if(ch_=='*'){
                        consume();
                        if(ch_=='/'){
                            consume();
                            break;
                        }
                    }else{
                        consume();
                    }
                }
                continue;
            }
            return{TokenId::OP_DIV,"/",line_,col_};

        }
        if(ch_=='"'){
            std::string l{};
            l+="\"";
            consume();
            while(ch_!='"'&&ch_!=EOF){
               if(ch_=='\\'){
                    l+=ch_;
                    consume();
                    l+=ch_;
                    consume();
               }else{
                  l+=ch_;
                   consume();
               }
            }
            l+="\"";
            consume();
            return{TokenId::STRING_LIT,l,line_,col_};
        }
        if(ch_>='a'&&ch_<='z'||ch_>='A'&&ch_<='Z'||ch_=='_'){
            std::string l{};
            while(ch_>='a'&&ch_<='z'||ch_>='A'&&ch_<='Z'||ch_>='0'&&ch_<='9'||ch_=='_'){
                l+=ch_;
                consume();
            }
            if(l=="int"){
                return{TokenId::KW_INT,l,line_,col_};
            }
            if(l=="bool"){
                return{TokenId::KW_BOOL,l,line_,col_};
            }
            if(l=="true"){
                return{TokenId::KW_TRUE,l,line_,col_};
            }
            if(l=="false"){
                return{TokenId::KW_FALSE,l,line_,col_};
            }
            if(l=="if"){
                return{TokenId::KW_IF,l,line_,col_};
            }
            if(l=="else"){
                return{TokenId::KW_ELSE,l,line_,col_};
            }
            if(l=="var"){
                return{TokenId::KW_VAR,l,line_,col_};
            }
            if(l=="func"){
                return{TokenId::KW_FUNC,l,line_,col_};
            }
            if(l=="return"){
                return{TokenId::KW_RETURN,l,line_,col_};
            }
            if(l=="ref"){
                return{TokenId::KW_REF,l,line_,col_};
            }
            if(l=="for"){
                return{TokenId::KW_FOR,l,line_,col_};
            }
            if(l=="print"){
                return{TokenId::KW_PRINT,l,line_,col_};
            }
            if(l=="println"){
                return{TokenId::KW_PRINTLN,l,line_,col_};
            }
            return{TokenId::IDENT,l,line_,col_};
        }
        if(ch_>='0'&&ch_<='9'){
            std::string l{};
            l+=ch_;
            consume();
            while(ch_>='0'&&ch_<='9'){
                l+=ch_;
                consume();
            }
            return{TokenId::INT_LIT,l,line_,col_};
        }
        if(ch_=='+'){
            consume();
            return{TokenId::OP_ADD,"+",line_,col_};
        }
        if(ch_=='-'){
            consume();
            return{TokenId::OP_SUB,"-",line_,col_};
        }
        if(ch_=='*'){
            consume();
            return{TokenId::OP_MUL,"*",line_,col_};
        }
        if(ch_=='%'){
            consume();
            return{TokenId::OP_MOD,"%",line_,col_};
        }
        if(ch_=='('){
            consume();
            return{TokenId::OPEN_PAR,"(",line_,col_};
        }
        if(ch_==')'){
            consume();
            return{TokenId::CLOSE_PAREN,")",line_,col_};
        }
        if(ch_=='{'){
            consume();
            return{TokenId::OPEN_BRACE,"{",line_,col_};
        }
        if(ch_=='}'){
            consume();
            return{TokenId::CLOSE_BRACE,"}",line_,col_};
        }
        if(ch_==','){
            consume();
            return{TokenId::COMMA,",",line_,col_};
        }
        if(ch_==';'){
            consume();
            return{TokenId::SEMICOLON,";",line_,col_};
        }
        if(ch_=='='){
            consume();
            if(ch_=='='){
                consume();
                return{TokenId::OP_EQ,"==",line_,col_};
            }
            return{TokenId::OP_ASSIGN,"=",line_,col_};
        }
        if(ch_=='!'){
            consume();
            if(ch_=='='){
                consume();
                return{TokenId::OP_NEQ,"!=",line_,col_};
            }
            return{TokenId::OP_NOT,"!",line_,col_};
        }
        if(ch_=='<'){
            consume();
            if(ch_=='='){
                consume();
                return{TokenId::OP_LTE,"<=",line_,col_};
            }
            return{TokenId::OP_LT,"<",line_,col_};
        }
        if(ch_=='>'){
            consume();
            if(ch_=='='){
                consume();
                return{TokenId::OP_GTE,">=",line_,col_};
            }
            return{TokenId::OP_GT,">",line_,col_};
        }
        if(ch_==':'){
            consume();
            if(ch_=='='){
                consume();
                return{TokenId::OP_SHORT_DECL,":=",line_,col_};
            }
            return{TokenId::UNK,":",line_,col_};
        }
        if(ch_=='&'){
            consume();
            if(ch_=='&'){
                consume();
                return{TokenId::OP_AND,"&&",line_,col_};
            }
            return{TokenId::OP_ADDR,"&",line_,col_};
        }
        if(ch_=='|'){
            consume();
            if(ch_=='|'){
                consume();
                return{TokenId::OP_OR,"||",line_,col_};
            }
            return{TokenId::UNK,"|",line_,col_};
        }
        if(ch_==EOF){
            return{TokenId::END_OF_FILE,"<<EOF>>",line_,col_};
        }
        {
            std::string l{};
            l+=ch_;
            consume();
            return{TokenId::UNK,l,line_,col_};
        }

    }while(true);

}